version: "3"
services:
  backend:
    build: .
    container_name: backend
    ports:
      - "5000:5000"
      - "9229:9229"  # Mapear el puerto de depuración
    environment:
      - NODE_ENV=development
      - PORT=5000
      - FRONTEND_URL=http://frontend:3000
      - DB_URL=mongodb://mongodb/catalogo
      - JWT_KEY=LLAVESECRETA
    depends_on:
      - mongodb
    tty: true    
  mongodb:
    image: mongo:7.0.6
    container_name: mongodb
    ports:
      - "27017:27017"